// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwyK_pPrpKwrDu35YwWYQ9Y614s5jSyo',
    appId: '1:844987318785:android:944be93cc63a7c069df600',
    messagingSenderId: '844987318785',
    projectId: 'coding-quiz-2b817',
    databaseURL: 'https://coding-quiz-2b817-default-rtdb.firebaseio.com',
    storageBucket: 'coding-quiz-2b817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQrfA993vqp2gbRXipI1RNfelmAt6PWGA',
    appId: '1:844987318785:ios:d9689675463b77a19df600',
    messagingSenderId: '844987318785',
    projectId: 'coding-quiz-2b817',
    databaseURL: 'https://coding-quiz-2b817-default-rtdb.firebaseio.com',
    storageBucket: 'coding-quiz-2b817.appspot.com',
    iosClientId: '844987318785-35jgcpvlkcq0h6u2uive6c45m28ogmbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingQuiz',
  );
}
